---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: test
  namespace: kubesphere-sample-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: ldmoko/myapp:v${BUILD_NUMBER}
        name: test
